version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}

  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    volumes:
      - ./parser:/app
    entrypoint: ["scrapy"]

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql

  apache:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./apache/apache2.conf:/etc/apache2/apache2.conf
