version: '3.8'

services:
  php:
    build:
      context: ./backend/php
    container_name: php-container
    networks:
      - my-network
    volumes:
      - ./backend/php/laravel:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    build:
      context: ./backend/db
    container_name: mysql-container
    networks:
      - my-network
    ports:
      - "3306:3306"

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    networks:
      - my-network
    ports:
      - "3000:3000"
    depends_on:
      - php
    stdin_open: true
    tty: true

  parser:
    build:
      context: ./parser
    container_name: parser-container
    networks:
      - my-network
    depends_on:
      - db
    volumes:
      - ./parser:/parser

networks:
  my-network:
    driver: bridge
