version: '3.8'

services:
 
  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    networks:
      - my-network
    ports:
      - "3000:3000"
    volumes: # Закоменить в продакшене
      - ./frontend:/frontend  # Закоменить в продакшене
      - /frontend/node_modules  # Закоменить в продакшене
    environment:  # Закоменить в продакшене
      - CHOKIDAR_USEPOLLING=true   # Закоменить в продакшене
      - WDS_SOCKET_PORT=3000   # Закоменить в продакшене
    stdin_open: true
    tty: true

  parser:
    build:
      context: ./parser
    container_name: parser-container
    networks:
      - my-network
    ports:
      - "5000:5000"
    volumes: # Закоменить в продакшене
      - ./parser:/parser # Закоменить в продакшене
    stdin_open: true
    tty: true

  mysql:
    build:
      context: ./mysql
    container_name: mysql-container
    networks:
      - my-network
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Закоменить в продакшене
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql # Закоменить в продакшене
      
networks:
  my-network:
    driver: bridge

volumes: # Закоменить в продакшене
  mysql_data: # Закоменить в продакшене
