nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*'] # Для разработки. В продакшене укажите конкретные домены
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false